# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

dist: trusty
sudo: required
services:
  - docker
language: generic
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - pyo@robotis.com
env:
  matrix:
    - ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu  USE_DEB=true
    - ROS_DISTRO="kinetic"   PRERELEASE=true PRERELEASE_DOWNSTREAM_DEPTH=0
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic"   PRERELEASE=true PRERELEASE_DOWNSTREAM_DEPTH=0
branches:
  only:
    - master
    - develop
    - kinetic-devel
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
  
