services:
  turtlebot3:
    container_name: turtlebot3
<<<<<<< HEAD:docker/jazzy/sbc/docker-compose.yml
    image: robotis/turtlebot3:jazzy-sbc-latest
=======
    image: robotis/turtlebot3:latest
>>>>>>> e0efe4fa4d6955cf2d14dac69194458cd564f2ad:docker/docker-compose.yml
    build:
      context: .
      dockerfile: Dockerfile.sbc
    tty: true
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    ipc: host
    pid: host
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./workspace:/workspace
      - ../:/root/turtlebot3_ws/src/turtlebot3
    privileged: true
    command: bash
