name: humble-devel

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ humble-devel ]
  pull_request:
    branches: [ humble-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  humble-devel:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          # - dashing
          # - foxy
          # - galactic
          - humble
          # - rolling
        include:
            # Dashing Diademata (May 2019 - May 2021)
          # - docker_image: ubuntu:bionic
          #   ros_distribution: dashing
          #   ros_version: 2
            # Foxy Fitzroy (June 2020 - May 2023)
          # - docker_image: ubuntu:focal
          #   ros_distribution: foxy
          #   ros_version: 2
            # Galactic Geochelone (May 2021)
          # - docker_image: ubuntu:focal
          #   ros_distribution: galactic
          #   ros_version: 2
            # Humble Hawksbill (May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
            # Rolling
          # - docker_image: ubuntu:jammy
          #   ros_distribution: rolling
          #   ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.2.5
        with:
          package-name: turtlebot3
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "https://raw.githubusercontent.com/ROBOTIS-GIT/turtlebot3/humble-devel/turtlebot3_ci.repos"
